Repository abhiramkg2000/HackOctober22, pull requests merged in 2022-10, with the labels that each got.

#3 added a program to swap two numbers in c
  swap.c
Labels: hacktoberfest-accepted

#4 Added a program to find fibonacci series in c
  fibonacci.c
Labels: good first issue, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#5 Added a program to find factorial of a number in C
  factorial.c
Labels: good first issue, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#12 Insertion & Merge Sort
  InsertionSort.cpp
  MergeSort.cpp
  SelectionSort.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#13 fastest and efficient binary search method in c++
  binary seach.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#16 Added code for stack and infixtopostfix expression
  infixtopostfix.c
  stack.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#26 Code for linkedlist and rockpaperandscissor
  C programs/linkedlist.c
  C programs/rockpaperandscissor.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#28 Added Maximum Path Sum Leetcode - HackterFest2022
  C++ programs/.vscode/settings.json
  C++ programs/MaximumPathSum.cpp
  C++ programs/Permutation.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#29 Program for NQueens
  Java programs/NQueens.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#30 Init
  Web Development/simpleTabs/index.html
  Web Development/simpleTabs/style.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#31 Removed .vscode folder
  C++ programs/.vscode/settings.json
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#32 loginPage
  Web Development/loginPage/index.html
  Web Development/loginPage/style.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#33 expenseTracker
  Web Development/toDoList/index.html
  Web Development/toDoList/script.js
  Web Development/toDoList/style.css
  Web Development/toDoList/trashbin.png
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#34 circular queue data structure added with menu operations
  C programs/Circularqueue.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#35 Running_sum.cpp
  C++ programs/Running_sum.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#37 Different Method to Print Hello World
  C programs/HelloWorld.c
Labels: good first issue, HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#45 wave_print_2D.cpp
  C programs/Matrix Addition.c
  C programs/fabonicseries.c
  C++ programs/AntiClockWise_Print_of_Spiral_Printing.cpp
  C++ programs/wave_print_2D.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#53 Rock Paper Scissors Game
  Web Development/Rock Paper Scissors Game/app.js
  Web Development/Rock Paper Scissors Game/index.html
  Web Development/Rock Paper Scissors Game/stylesheet.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#48 brracket_balance.cpp (STACK)
  C++ programs/brracket_balance.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#49 infix_to_postfix.cpp (STACK)
  C programs/bubble_sorting.c
  C++ programs/infix_to_postfix.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#50 stack_impemented_by_linked-list.cpp
  C++ programs/stack_impemented_by_ll.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#51 print_row_from_pasacl.cpp
  C programs/cashier_problem.c
  C++ programs/print_row_from_pasacl.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#52 pascal_matrix.cpp
  C programs/leap_year.c
  C++ programs/pascal_matrix.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#56 Create 1sCompliment.cpp
  C++ programs/1sCompliment.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#54 added prims algorithm
  C++ programs/prims_algo.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#57 Calculate the Square of a Number
  C programs/ChangeTwoDigitInNumberInEnglish.c
  C programs/Square.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#58 Digital StopWatch
  Web Development/Digital StopWatch/app.js
  Web Development/Digital StopWatch/index.html
  Web Development/Digital StopWatch/stylesheet.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#59 Create SelectionSort.java
  C++ programs/sorting
  Java programs/SelectionSort.java
  Java programs/gcd.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#60 Password Strength Checker
  Web Development/Password Strength Checker/app.js
  Web Development/Password Strength Checker/index.html
  Web Development/Password Strength Checker/stylesheet.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#62 Create max
  Java programs/Rotate.java
  Java programs/max
  Java programs/merge_sort
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#63 Create TowerOfHanoi.java
  Java programs/TowerOfHanoi.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#64 Create QuickSort.java
  Java programs/QuickSort.java
  Java programs/loopdetectioninLL.java
  Java programs/rainwater.java
  unionintersection.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#70 Optimized UI for the game
  Web Development/Rock Paper Scissors Game/download.jpg
  Web Development/Rock Paper Scissors Game/g.jpg
  Web Development/Rock Paper Scissors Game/stylesheet.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#71 codechef 3 star to 4 star question answered very less
  Java programs/BOOKCHEF.java
  Java programs/SMPAIR.java
  Java programs/TACHSTCK.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#72 Create Max.java
  Java programs/Max.java
  Java programs/MergeSort.java
  heapsort.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#78 Linked List
  Java programs/LinkedList.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#79 CombinationSum
  Java programs/CombinationSum.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#83 added stack.java
  Java programs/stack.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#87 armstrong.java
  Java programs/armstrong.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#88 transpose.c
  C programs/transpose.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#90 zerosumtriplet.java
  Java programs/rainwater.java
  Java programs/zerosumtriplet.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#91 removeduplicates.java
  Java programs/removeduplicates.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#92 Trapping Rainwater Problem
  C++ programs/Trapping_Rainwater.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#93 Create find_path.java
  Java programs/find_path.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#94 Create suduko.java
  Java programs/suduko.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#96 Create dog.java
  Java programs/dog.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#99 Largest Sum Contiguous Subarray
  C++ programs/Kadane's__Algorithm.cpp
  Web Development/TIC-TAC-TOE/index.html
  Web Development/TIC-TAC-TOE/tic.css
  Web Development/TIC-TAC-TOE/tic.js
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#100 xoxo game
  Java programs/xoxo.java
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#101 Snake Game
  C programs/snakegame.c
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#107 Python
  Python/Calculator.py
  Python/Creating _cross.py
  Python/Snake and Ladder/Snake_and_ladder.py
  Python/Snake and Ladder/snake_and_ladder.png
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#108 Basic node app for adding text in .txt file
  Web Development/file_handling/.gitignore
  Web Development/file_handling/app.js
  Web Development/file_handling/file_store.js
  Web Development/file_handling/hello.text
  Web Development/file_handling/meesage.txt
  Web Development/file_handling/message.txt
  Web Development/file_handling/package-lock.json
  Web Development/file_handling/package.json
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#113 Create C++ program to check Valid Shuffle
  C++ programs/C++ program to check Valid Shuffle
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#114 Create Python Program to check whether input is well-formatted
  Python/Python Program to check whether input is well-formatted
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#115 Create Create C++ Programs to check string rotation
  C++ programs/Create C++ Programs to check string rotation
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#117 Create C++ program to Create Spiral Matrix
  C++ programs/C++ program to Create Spiral Matrix
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#120 To do list
  Web Development/todoslist project/index.html
  Web Development/todoslist project/script.js
  Web Development/todoslist project/style.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#122 Create bubblesort.cpp
  C++ programs/bubblesort.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#123 C++ Programs
  C++ programs/access array elements.cpp
  C++ programs/add to integers.cpp
  C++ programs/add two numbers using functions.cpp
  C++ programs/addition and subtraction of a 2-D matrix.cpp
  C++ programs/addition of two matrices.cpp
  C++ programs/age of person in years,week,days,hours.cpp
  C++ programs/all prime numbers between 1 to n.cpp
  C++ programs/alphabet pattern 1.cpp
  C++ programs/alphabet pattern 2.cpp
  C++ programs/alphabet pattern 3.cpp
  C++ programs/alphabet pattern in v shape.cpp
  C++ programs/alphabet pattern.cpp
  C++ programs/alphabets pattern in inverted U shap.cpp
  C++ programs/area of rectangle using functions.cpp
  C++ programs/area of square using functions.cpp
  C++ programs/armstrong number using functions.cpp
  C++ programs/armstrong number.cpp
  C++ programs/armstrong numbr using recursion.cpp
  C++ programs/array using switch case.cpp
  C++ programs/arrays using switch case.cpp
  C++ programs/average of 5 numbers using pointers with no arguments, no returns.cpp
  C++ programs/average of numbers using arrays.cpp
  C++ programs/binary pattern.cpp
  C++ programs/calculate aggergate percentage of a student.cpp
  C++ programs/calculate gross salary.cpp
  C++ programs/calculate sum and average of first 10 integer numbers.cpp
  C++ programs/calculate sum of odd and even from 1 to n using loops.cpp
  C++ programs/call by reference using functions.cpp
  C++ programs/character is vowel or consonant in string using pointers.cpp
  C++ programs/check a given character is lower case alphabet or not.cpp
  C++ programs/check a number is positive,negative,zero.cpp
  C++ programs/check even or odd number.cpp
  C++ programs/check odd or even using functions.cpp
  C++ programs/check pime or not using functions.cpp
  C++ programs/check vowel or consonant.cpp
  C++ programs/check whether a input character if it is lowercase letter then convert to uppercase letter otherwise convert to lower case letter.cpp
  C++ programs/check whether a triangle is valid or not.cpp
  C++ programs/compute sum of all array elements.cpp
  C++ programs/convert degree fahrenheit into degree celsius.cpp
  C++ programs/convert distance in meters,feet,inches,centimeters.cpp
  C++ programs/copy one array to another.cpp
  C++ programs/cost price of an item.cpp
  C++ programs/count how many times a number is present in an array.cpp
  C++ programs/count number of positive,negative and zero in array.cpp
  C++ programs/count positive,negative,zero elements in an aray.cpp
  C++ programs/cross star pattern with value of n.cpp
  C++ programs/cross star pattern.cpp
  C++ programs/cube of a number using functions.cpp
  C++ programs/date of birth of a person.cpp
  C++ programs/delete element from an array.cpp
  C++ programs/deletion of array elementys.cpp
  C++ programs/determine a number is prime or not.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#125 Create Topological Sort in C++
  C++ programs/Topological Sort in C++
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#126 Netflix clone
  Web Development/netflix clone/index.html
  Web Development/netflix clone/script.js
  Web Development/netflix clone/style.css
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#129 HeapSort.cpp
  C++ programs/HeapSort.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022

#131 Create editdistance.cpp
  C++ programs/editdistance.cpp
Labels: HACKTOBERFEST-ACCEPTED, HACKTOBERFEST-2022
